/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import publictransport.DB.Tableo;
import publictransport.DB.TableroImagen;

public class DeleteCliente extends javax.swing.JFrame {

    public String cedula;
    public String nombre;
    public String apellido;
    public String telefono;
    public String TipoUsuario;
    public double saldo;
    public String fecha;
    public String ss1;
    
    public DeleteCliente() {
        initComponents();
        setTitle("Eliminar Cliente");
        setBounds(700, 300, 700, 520);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ciField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        apellidosField = new javax.swing.JTextField();
        fechaNacField = new javax.swing.JTextField();
        telefonoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fts = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ELIMINAR CLIENTE DE LA BD");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.setAutoscrolls(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 460, 30));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        ciField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ciField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ciField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 125, 260, 30));

        nombreField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 260, 30));

        apellidosField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(apellidosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 260, 30));

        fechaNacField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(fechaNacField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 260, 30));

        telefonoField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(telefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 260, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("CEDULA DE IDENTIDAD:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("NACIMIENTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("TELEFONO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fts);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, 150));

        jLabel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publictransport/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Tableo datoscliente = new Tableo();
        TableroImagen ti = new TableroImagen();
        
                
        File archivo;
        JFileChooser flcArchivo = new JFileChooser();
        flcArchivo.setFileFilter(new FileNameExtensionFilter("Archivo de Imagen","jpg","jpeg","png"));
                
        cedula=ciField.getText();
        ss1 = ti.getUrlImagen(cedula);
        System.out.println("bucando Imagen con cedula: "+this.cedula);  
        
        archivo = flcArchivo.getSelectedFile();
        Image fts1 = getToolkit().getImage(ss1);
        fts1 = fts1.getScaledInstance(220, 300, 1);
        fts.setIcon(new ImageIcon(fts1));
        
        /*
        try {
            datoscliente.getDatos(cedula);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteCliente.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        nombre=datoscliente.getNombre(cedula);
        apellido=datoscliente.getApellido(cedula);
        fecha=datoscliente.getFecha(cedula);
        telefono=datoscliente.getTelefono(cedula);
                
        nombreField.setText(nombre);
        apellidosField.setText(apellido);
        fechaNacField.setText(fecha);
        telefonoField.setText(telefono);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ciFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tableo elimindor = new Tableo();
        TableroImagen ti = new TableroImagen();
        
        ti.deleteImagen(this.cedula);
        elimindor.deleteCliente(this.cedula);
        
        System.out.println("Se elimino la persona con la cedula "+this.cedula);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosField;
    private javax.swing.JTextField ciField;
    private javax.swing.JTextField fechaNacField;
    private javax.swing.JLabel fts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
