/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import GeneradorQR.GeneradorQR;
import Impresora.Imprimir_JPanel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import publictransport.DB.Tableo;
import publictransport.DB.TableroImagen;

/**
 *
 * @author CASPED
 */
public class DesigningCards extends javax.swing.JFrame {

    ImageIcon Imagen[]=new ImageIcon[5];
    int cont=1; 
    
    public DesigningCards() {
        initComponents();
        setTitle("Targuetero");
        setBounds(700, 300, 700, 520);
        this.setLocationRelativeTo(null);
        
        for(int i=0;i<5;i++){
            Imagen[i]=new ImageIcon (getClass().getResource("/publictransport/imagenes/card"+i+".png"));
        }
        
        jLabel1.setIcon(Imagen[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimir = new javax.swing.JPanel();
        fts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jtxtcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        generarQR = new javax.swing.JButton();
        cargarDatos = new javax.swing.JButton();
        imprimir1 = new javax.swing.JButton();
        jtxtcedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imprimir.setBackground(new java.awt.Color(255, 255, 255));
        imprimir.setForeground(new java.awt.Color(255, 255, 255));
        imprimir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        imprimir.add(fts, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 56, 132, 160));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE:");
        imprimir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDO:");
        imprimir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No.");
        jLabel6.setVerifyInputWhenFocusTarget(false);
        imprimir.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        imprimir.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 260, 30));

        jTextApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imprimir.add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 260, 30));

        jtxtcodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoActionPerformed(evt);
            }
        });
        imprimir.add(jtxtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publictransport/imagenes/card2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(243, 153));
        imprimir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 486, 306));

        getContentPane().add(imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, 330));

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        generarQR.setText("Generar QR");
        generarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarQRActionPerformed(evt);
            }
        });
        getContentPane().add(generarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        cargarDatos.setText("Cargar Datos");
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(cargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        imprimir1.setText("Imprimir");
        imprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimir1ActionPerformed(evt);
            }
        });
        getContentPane().add(imprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jtxtcedula.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jtxtcedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcedula.setToolTipText("");
        jtxtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 32, 120, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publictransport/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        if(cont==1){
            cont=5;
        }
        cont--;
        jLabel1.setIcon(Imagen[cont]);
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        if(cont==5){
            cont=0;
        }
        cont++;
        jLabel1.setIcon(Imagen[cont]);
    }//GEN-LAST:event_siguienteActionPerformed

    private void generarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarQRActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String texto=jtxtcedula.getText();
                System.out.println("Generar QR:" + texto);
                new GeneradorQR(texto).setVisible(false);
            }
        });
    }//GEN-LAST:event_generarQRActionPerformed

    private void imprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimir1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Imprimir_JPanel imprimir_JPanel = new Imprimir_JPanel(imprimir);
            }
        });
    }//GEN-LAST:event_imprimir1ActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewPerson newPerson = new NewPerson();
                nombre=newPerson.getNombre();
                jTextNombre.setText(nombre);
            }
        });*/
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jtxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
        
        Tableo datoscliente = new Tableo();
        TableroImagen ti = new TableroImagen();
                          
        String cedula=jtxtcedula.getText();
        String ss = ti.getUrlImagen(cedula);            
        
        File archivo;
        JFileChooser flcArchivo = new JFileChooser();
        flcArchivo.setFileFilter(new FileNameExtensionFilter("Archivo de Imagen","jpg","jpeg","png"));
        
        archivo = flcArchivo.getSelectedFile();
        Image fts1 = getToolkit().getImage(ss);
        fts1 = fts1.getScaledInstance(120, 150, 1);
        fts.setIcon(new ImageIcon(fts1));
        
        String nombre=datoscliente.getNombre(cedula);
        String apellidos=datoscliente.getApellido(cedula);
        
        jTextNombre.setText(nombre);
        jTextApellido.setText(apellidos);
        jtxtcodigo.setText(cedula);
                
        System.out.println("nombre:" + nombre);
        System.out.println("apellido:" + apellidos);
        System.out.println("cedula:" + cedula);
              
    }//GEN-LAST:event_cargarDatosActionPerformed
    
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // setIcon(null);
        fts.setIcon(null);
        jTextNombre.setText(null);
        jTextApellido.setText(null);
        jtxtcodigo.setText(null);
    }//GEN-LAST:event_limpiarActionPerformed

    private void jtxtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesigningCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesigningCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesigningCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesigningCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DesigningCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton cargarDatos;
    private javax.swing.JLabel fts;
    private javax.swing.JButton generarQR;
    private javax.swing.JPanel imprimir;
    private javax.swing.JButton imprimir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jtxtcedula;
    private javax.swing.JTextField jtxtcodigo;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables

}
